-- Q1: What is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount_usd) as revenue
from customers
group by gender;

-- Q2: Which customers used a discount but spent more than average?

SELECT customer_id, purchase_amount_usd
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (
        SELECT AVG(purchase_amount_usd)
        FROM customers
  );

-- Q3 which are the top 5 products with the highest average reviewrating?

SELECT 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS `average product rating`
FROM customers
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS DECIMAL(10,2))) DESC
LIMIT 5;

-- Q4:compare the average purchase amounts between standard and express shipping

select shipping_type,
avg(purchase_amount_usd)
from customers
where shipping_type in ('standard','Express')
group by shipping_type;


-- Q5. do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount_usd),2) as avg_spend,
round(sum(purchase_amount_usd),2) as total_revenue
from customers
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*),
    2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. segment customers into new returning and loyal based on their total number of previous purchases ,and show the count of each segment 

with customer_type as(
select customer_id,previous_purchases,
case
when previous_purchases =1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else  'loyal'
end as customer_segment 
from customers)
select customer_segment,count(*) as "number of customers"
from customer_type 
group by customer_segment;

-- Q8: what are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
	FROM item_counts
where item_rank<=3;


-- Q9: are customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases >=5
group by subscription_status;

-- Q10: what is the revenue contribution of each group ?

select age_group,
sum(purchase_amount_usd) as total_revenue
from customers
group by age_group
order by total_revenue desc;
